### ISSUE TITLE
Positioning

### ISSUE THREAD

**Issue by seanohue** [RanvierMUD/core#15]
Implement positioning (necessary for some commands such as "sleep", could also be interesting to use a "knockdown" skill to change the positioning of other characters).

Basically, some commands will only be available in certain positions: laying, sitting, or standing, for example.

`sleep`, for instance, would give a huge boost to health/energy/mana regen but would change the player character's position, which would affect which commands are available and even affect the way they receive certain inputs (such as not being able to "hear" someone in the same room `say`ing something while they are asleep).

This could be implemented via having an attribute on the PC to describe their position (on all characters, in fact), commands to change their position (`stand` to recover from being knocked down before they can fight back, for example), and then a property on command objects to list any blacklisted positions (or whitelisted ones, either way is fine). For instance:

```
// look command config
return {
    usage: "look [thing]",
    blacklistedPositions: ["sleeping"],
    command: state => (args, player) => { } // etc. etc.
    }
```

This is just a suggestion as far as implementation goes, there is probably a better way 🌵 .

**Comment by ratacat** [comment]
I love it, not sure if this affects the structure of it at all, but it would also be really cool to be able to apply a damage modifier to a character in different positions, and maybe affect hit %.  For example, if a character has been bashed (is prone), they should take 120% melee damage.  And if a character is asleep, it should be MUCH easier to land a hit on them (which probably wakes them up).

**Comment by seanohue** [comment]
This would be a great feature to include in a bundle rather than core, as it could all be handled with the effects system and various commands.
