### ISSUE TITLE
Allow for NPCs to respond to certain channel broadcasts.

### ISSUE THREAD

**Issue by ratacat** [RanvierMUD/core#22]
Say seems to be the most obvious choice. Although perhaps a case could be made for tell (maybe just searching room for npc target, instead of whole area/mud). 

I'm less sure about yell.  Maybe supporting it wouldn't hurt, perhaps yelling for the guards, or a thief, would be useful, and could be executed by other NPCs, not necessarily players. 

As for chat, maybe somebody would want to integrate some mudwide events, statistics, etc into a NPC announcer or something.  Or perhaps an NPC that scans chat channels for common newbie questions and sends a tell to the player with helpful suggestions.  I dunno.  Just thoughts.

**Comment by shawncplus** [comment]
My general thought is this: update `Broadcast` to always emit at `channelReceive` event on the target. If the target does not have a socket, only emit the event, if they do have a socket write to it.

* Update `Character#getBroadcastTargets` to always return `[this]`
* Update `Audience` classes and Broadcastable entities to include NPCs and the entity itself, e.g., a Room is a valid broadcastable target. I can imagine a Room script where a player has to say a magic word to reveal an item/spawn an NPC/etc.
