### ISSUE TITLE
Item.belongsTo doesn't work for NPCs

### ISSUE THREAD

**Issue by markscho** [RanvierMUD/core#25]
If an item is on an NPC, Item.belongsTo() returns FALSE, yet the value of the property does still point to the NPC that possesses it.  I'd like to see this opened up so that it points to either an NPC or a Player.  And while we're at it, I'd also like to rename this property to any one of the following:
- possessedBy
- with
- carriedBy
Just because an item is in your possession, doesn't make you the "owner".  This allows us to establish our own ideas of ownership.

**Comment by seanohue** [comment]
I like `carriedBy` as an API, so that developers can also use stuff like `belongsTo` to implement things like theft.

**Comment by shawncplus** [comment]
I think you mean `findOwner()` returns false, `belongsTo` is never `false`. The `belongsTo` property is meant to be `is in the inventory of...`. Its original purpose was not "I own this item" from a perspective of "Who owned this originally".

The purpose of `findOwner()` was to allow you to find the `Character` that ultimately had the item along a series of inventories, for example: Player A is carrying a bag TestBag, and inside TestBag, is another bag called InnerBag, and inside InnerBag is a sword, TestSword.

In that case `sword.findOwner()` should return Player A. I agree it's very silly that this doesn't work for NPCs, I don't know why that's the case, it shouldn't. An NPC is just as likely to have an item as a player. Perhaps the method should be renamed to `findHolder()` or something that better describes its purpose which has really nothing to do with the kind of "ownership" you're talking about.
