### ISSUE TITLE
Character follow methods should emit events.

### ISSUE THREAD

**Issue by markscho** [RanvierMUD/core#26]
Currently, when Player.moveTo() is called, the following emits are made, triggering the appropriate messages sent to all relevant players:
    nextRoom.emit('playerEnter', this);
    this.emit('enterRoom', nextRoom);

Similarly, all four follow methods should do the same, in so far as using an emit to trigger an event, which then performs the logic of informing all relevant players of the action.

**Comment by shawncplus** [comment]
Have this sitting on a branch because I was also missing events for items being opened/closed/locked/unlocked and a few others along with missing documentation for said events. If I don't push this tomorrow night comment on this issue to remind me
