### ISSUE TITLE
Item doesn't serialize all of its mutable properties; missing type, name, keywords, description, and roomdesc

### ISSUE THREAD

**Issue by ratacat** [RanvierMUD/core#27]
I starting building a basic system for random equipment generation. And realized after getting into it that none of the items would survive a logout/quit. Diving into it a bit, it seems the current serialize / hydrate methods for Inventory and/or Items are relying on looking up the EntityReference for the item's ID, TYPE, NAME, KEYWORDS, DESCRIPTION, and ROOMDESC. All the metadata serializes and hydrates fine. It seems that an implication of this is that you wouldn't be able to make randomly generated equipment(that persists) without modifying core.  

The only place I could see a possibility of that, is writing an ancillary save function that is called on the save event at @bundles/ranvier-player-events/player-events.js, to save items without EntityReference data, and I'm not sure where you could load it.

Alternatively if we look at what we could change in core, I think it would either mean changing all items over to serializing their entire object, or providing a hook of some sort for a bundle to serialize/hydrate items not defined with an EntityReference on disk.

*edits* 
After talking with Nephila, it seems like there might be a sort of solution around writing the randomly generated items to datastore in their own zone.  So that they hydrate properly from the EntityReference.  Although we both think that maybe the bigger issue is the question around whether Items once created, persist and can be modified on their own, or whether they are 're-created' from their original form on login.

**Comment by shawncplus** [comment]
Looking at the method you're correct. It's only serializing locked/closed state, metadata, behaviors, and inventory. Which isn't enough if, as you mention, dynamically generate an item from some base item and change its name/roomDesc/description/type/keywords. I don't see any reason why they shouldn't be.

>  question around whether Items once created, persist and can be modified on their own, or whether they are 're-created' from their original form on login.

The way serialization/hydration works is as you describe: items are serialized into some pure-data version, then they disappear. When it needs to be loaded into the game we create a plain item from the original definition, then `hydrate()` say "Hey, this is what your old state used to be" and the goal is that after hydration the item is in the same state it was before it disappeared.
