### ISSUE TITLE
Other issues with randomly generated items

### ISSUE THREAD

**Issue by ratacat** [RanvierMUD/core#31]
Okay, I'm deleting original comment here to provide a more clear idea of things.

The item hydration path overview looks like this
`Inventory.hydrate` ->
`state.ItemFactory.create` ->
`EntityFactory.createByType` ->
`Item.constructor`

In Inventory.hydrate, the call to the ItemFactory.create is only passing in the entityReference to be used in the initial call of creating the item, even though Inventory.hydrate has the serialized item Definition. Thus none of the later methods are even accessing the serialized data. I took a shot at addressing this by adding in the serialized definition to this chain...

```
  hydrate(state, belongsTo) {
    // Item is imported here to prevent circular dependency with Item having an Inventory
    const Item = require('./Item');

    for (const [uuid, def] of this) {
      if (def instanceof Item) {
        def.belongsTo = belongsTo;
        continue;
      }

      if (!def.entityReference) {
        continue;
      }

      const area = state.AreaManager.getAreaByReference(def.entityReference);
      //==============added def as third argument on line below===============
      let newItem = state.ItemFactory.create(area, def.entityReference, def); 
      newItem.uuid = uuid;
      newItem.belongsTo = belongsTo;
      newItem.initializeInventory(def.inventory);
      newItem.hydrate(state, def);
      this.set(uuid, newItem);
      state.ItemManager.add(newItem);
    }
  }
}
```
then in ItemFactory
```
create(area, entityRef, def = {}) { // <-- added def here===========
    const item = this.createByType(area, entityRef, Item, def); <-- and here============
    item.area = area;
    return item;
  }
```

and EntityFactory
```
createByType(area, entityRef, Type, def = {}) { // <--- here=============
    const definition = this.getDefinition(entityRef) || def; <--- here===========
    /*
    if (!definition) {
      throw new Error('No Entity definition found for ' + entityRef)
    }
    */
    const entity = new Type(area, definition);

    if (this.scripts.has(entityRef)) {
      this.scripts.get(entityRef).attach(entity);
    }

    return entity;
  }
```

Which seems to successfully rebuild the items from the serialized data, instead of from the entityReference.

The only issue remaining after this that I've found with making randomly generated equipment survive serialization, is that it currently seems to lose it's TYPE, which is a SYMBOL.  I attempted to add 
`      type: this.type, `
to the Item.serialize method...however it would appear that JSON.stringify will strip out any properties with symbols for a value.  So Item.constructor method will set the TYPE of the item to Object as it's default since the serialized item no longer has a type. I haven't figured out what to do about this yet.

**Comment by ratacat** [comment]
Also attaching my prototype for random item generation if you want to test against it
https://www.dropbox.com/s/asz4qsefqjmfrtn/enceladus-random-generators.zip?dl=0

**Comment by shawncplus** [comment]
A few things:

> none of the later methods are even accessing the serialized data.

I don't know what you mean here and haven't heard a convincing argument for why you would need it.

> The only issue remaining after this that I've found with making randomly generated equipment survive serialization, is that it currently seems to lose it's TYPE, which is a SYMBOL.

I feel like if you're using item as the base for your randomly generated item and you're changing it _so much_ during generation that you're changing the type then you should use a different base item.

**Comment by shawncplus** [comment]
At the moment it's very much working as intended. The current engine does not support the dynamic creation of items without a base item which has a real entityReference.

The reason is exactly the thing you've ran into here. If you try to create an item out of thin air with an invalid, or non-existent, base item when that gets serialized to a player you've essentially created a null pointer because it doesn't have a valid entityReference. Which means that when the player logs in that item will vanish into thin air if not crash the server entirely.

The way the hydration system was originally made was intended for a type of random generation wherein you would have a _real_ base item and the randomly generated parts would modify `properties` while keeping the base item the same. Think WoW/Diablo style affixes "Iron Sword of the Fox". Whole-cloth generation is not a workflow I plan on supporting at the moment. If you want to randomly generate items do so from a real base item from a datasource with an entityReference.

**Comment by ratacat** [comment]
> The reason is exactly the thing you've ran into here. If you try to create an item out of thin air with an invalid, or non-existent, base item when that gets serialized to a player you've essentially created a null pointer because it doesn't have a valid entityReference. Which means that when the player logs in that item will vanish into thin air if not crash the server entirely.

Cool, that's fine! Thanks for the help Shawn, I'm not trying to be a pain in the ass!  
I'll use a base item definition in the zone. That's a great solution for me.  I'm closing this issue and have opened #34 as a hopefully a more specific example of the bug I was trying to talk about.
