### ISSUE TITLE
moveTo on Npc and Player should pass the previousRoom to the event

### ISSUE THREAD

**Issue by atarsha** [RanvierMUD/core#40]
When you think about the fact that Npc passes nextRoom to the event: `this.room.emit('npcLeave', this, nextRoom);` (thisRoom can determine the direction the Npc went based on nextRoom)

Then, why shouldn't nextRoom also received thisRoom as an argument of where the npc arrived from instead of just `nextRoom.emit('npcEnter', this);`

I think this should be added to the moveTo method of both Npc and Player as they both work the same way.

**Comment by shawncplus** [comment]
I agree

**Comment by atarsha** [comment]
Okay great. I'll put a PR together :)

**Comment by atarsha** [comment]
I take it back. (ignore the previous commit on my fork.) I spent some more time tinkering with it after that commit and didn't get it working correctly. Looks like I won't be throwing a PR together for this, at least not immediately.
