### ISSUE TITLE
lostFollower emit breaks teleport because follower is undefined

### ISSUE THREAD

**Issue by atarsha** [RanvierMUD/core#45]
Error on line 537 of Character.js

when emitting lostFollower, follower is undefined. Passing target instead.

This is evident in the code and causes a reproducible issue in game:

Log in, `teleport limbo:black` where the puppy will start following you. Go `west`, then `teleport limbo:black` again. Check your Ranvier logs for the undefined error.

**Comment by seanohue** [comment]
Good catch! LGTM, though I haven't tested it locally yet.
