### ISSUE TITLE
NPC Class

### ISSUE THREAD

**Issue by illusaen** [RanvierMUD/core#99]
Is there a built-in way to set NPC class/race combo so that the NPC's health can auto-calculate?

**Comment by shawncplus** [comment]
The core doesn't have a concept of race/class for anything. That's all down to bundle-developers to decide on how they want to handle that. The simplest approach is in the `metadata` of NPCs/Players. The docs for attributes have this exact case as an example: 

https://ranviermud.com/coding/attributes/#classrace-modifiers
